name: Build Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML file
        run: yamllint data.yml

      - name: Install dependencies
        run: cd .github/bin && composer install

      - name: Run the build script
        run: php .github/bin/build.php
