name: Build Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML file
        run: yamllint data.yml

      - name: Convert YAML to JSON
        run: python3 -c 'import sys, yaml, json; json.dump(yaml.safe_load(sys.stdin), sys.stdout, indent=4)' < data.yml > data.json

      - name: Display JSON
        run: cat data.json

      - name: Assert JSON is valid
        run: jq empty data.json
