name: Validate YAML

on:
  push:
  pull_request:

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: cd .github/bin && composer install

      - name: Validate YAML file
        run: php .github/bin/build.php lint < data.yml
