name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-yaml:
    name: Validate YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: cd .github/bin && composer install

      - name: Validate YAML file
        run: php .github/bin/build.php lint < data.yml

  build:
    name: Build Site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: cd .github/bin && composer install

      - name: Validate YAML file
        run: php .github/bin/build.php lint < data.yml

      - name: Convert YAML to JSON
        run: |
          php .github/bin/build.php convert < data.yml > data.json
          cat data.json

      - name: Build site
        run: php .github/bin/build.php build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    name: Deploy Site
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
